--
-- PostgreSQL database dump
--

\restrict nINp20zDhhKszaVVNoArGYu9zcLYodNc7VDl8OEMmp2lslEIYMR4UjQmKbFiP7y

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: aimodel; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.aimodel (
    id integer NOT NULL,
    created_at timestamp(6) without time zone,
    created_by integer,
    deleted_at timestamp(6) without time zone,
    deleted_by integer,
    is_delete boolean,
    updated_at timestamp(6) without time zone,
    updated_by integer,
    is_active boolean,
    model_description character varying(255),
    model_file_path character varying(500),
    model_name character varying(100),
    model_version character varying(50),
    croptype_id integer,
    description text
);


ALTER TABLE public.aimodel OWNER TO postgres;

--
-- Name: aimodel_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.aimodel ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.aimodel_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: area_infor; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.area_infor (
    id integer NOT NULL,
    created_at timestamp(6) without time zone,
    created_by integer,
    deleted_at timestamp(6) without time zone,
    deleted_by integer,
    is_delete boolean,
    updated_at timestamp(6) without time zone,
    updated_by integer,
    address character varying(255),
    area double precision,
    area_code character varying(50),
    area_name character varying(100),
    confirmed boolean,
    description character varying(255),
    latitude double precision,
    longitude double precision,
    province character varying(100),
    user_id integer
);


ALTER TABLE public.area_infor OWNER TO postgres;

--
-- Name: area_infor_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.area_infor ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.area_infor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: attachment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.attachment (
    id integer NOT NULL,
    created_at timestamp(6) without time zone,
    created_by integer,
    deleted_at timestamp(6) without time zone,
    deleted_by integer,
    is_delete boolean,
    updated_at timestamp(6) without time zone,
    updated_by integer,
    category character varying(50),
    file_name character varying(255),
    file_size bigint,
    file_type character varying(50),
    file_url character varying(500),
    mime_type character varying(100),
    reference_id integer,
    reference_type character varying(50)
);


ALTER TABLE public.attachment OWNER TO postgres;

--
-- Name: attachment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.attachment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.attachment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chat_message; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.chat_message (
    id integer NOT NULL,
    created_at timestamp(6) without time zone,
    created_by integer,
    deleted_at timestamp(6) without time zone,
    deleted_by integer,
    is_delete boolean,
    updated_at timestamp(6) without time zone,
    updated_by integer,
    imageurl character varying(255),
    message_content text,
    sender_type character varying(255),
    session_id integer,
    CONSTRAINT chat_message_sender_type_check CHECK (((sender_type)::text = ANY ((ARRAY['USER'::character varying, 'AI'::character varying])::text[])))
);


ALTER TABLE public.chat_message OWNER TO postgres;

--
-- Name: chat_message_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.chat_message ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_message_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chat_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.chat_session (
    id integer NOT NULL,
    created_at timestamp(6) without time zone,
    created_by integer,
    deleted_at timestamp(6) without time zone,
    deleted_by integer,
    is_delete boolean,
    updated_at timestamp(6) without time zone,
    updated_by integer,
    lastmessage_at timestamp(6) without time zone,
    session_title character varying(255),
    user_id integer,
    last_message text,
    last_message_at timestamp(6) without time zone
);


ALTER TABLE public.chat_session OWNER TO postgres;

--
-- Name: chat_session_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.chat_session ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_session_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: crop_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.crop_type (
    id integer NOT NULL,
    created_at timestamp(6) without time zone,
    created_by integer,
    deleted_at timestamp(6) without time zone,
    deleted_by integer,
    is_delete boolean,
    updated_at timestamp(6) without time zone,
    updated_by integer,
    crop_description character varying(255),
    crop_name character varying(100),
    cropname_en character varying(100),
    iconurl character varying(500),
    is_active boolean,
    description character varying(255)
);


ALTER TABLE public.crop_type OWNER TO postgres;

--
-- Name: crop_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.crop_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.crop_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: diagnose_history; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.diagnose_history (
    id integer NOT NULL,
    created_at timestamp(6) without time zone,
    created_by integer,
    deleted_at timestamp(6) without time zone,
    deleted_by integer,
    is_delete boolean,
    updated_at timestamp(6) without time zone,
    updated_by integer,
    originalimageurl character varying(255),
    status character varying(255),
    weather_data text,
    areainfo_id integer,
    croptype_id integer,
    user_id integer,
    latitude double precision,
    longitude double precision,
    CONSTRAINT diagnose_history_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying])::text[])))
);


ALTER TABLE public.diagnose_history OWNER TO postgres;

--
-- Name: diagnose_history_detail; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.diagnose_history_detail (
    id integer NOT NULL,
    created_at timestamp(6) without time zone,
    created_by integer,
    deleted_at timestamp(6) without time zone,
    deleted_by integer,
    is_delete boolean,
    updated_at timestamp(6) without time zone,
    updated_by integer,
    confidence_score numeric(5,4),
    cultivation_data text,
    risk_warning character varying(255),
    severity_level character varying(255),
    treatment_data text,
    diagnosehistory_id integer,
    disease_id integer,
    CONSTRAINT diagnose_history_detail_severity_level_check CHECK (((severity_level)::text = ANY ((ARRAY['NHE'::character varying, 'TRUNG_BINH'::character varying, 'NANG'::character varying])::text[])))
);


ALTER TABLE public.diagnose_history_detail OWNER TO postgres;

--
-- Name: diagnose_history_detail_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.diagnose_history_detail ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.diagnose_history_detail_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: diagnose_history_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.diagnose_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.diagnose_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: diagnose_review; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.diagnose_review (
    id integer NOT NULL,
    created_at timestamp(6) without time zone,
    created_by integer,
    deleted_at timestamp(6) without time zone,
    deleted_by integer,
    is_delete boolean,
    updated_at timestamp(6) without time zone,
    updated_by integer,
    comment character varying(255),
    is_accurate boolean,
    rating integer,
    reviewed_at timestamp(6) without time zone,
    diagnose_id integer,
    user_id integer,
    feedback text,
    history_id integer NOT NULL
);


ALTER TABLE public.diagnose_review OWNER TO postgres;

--
-- Name: diagnose_review_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.diagnose_review ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.diagnose_review_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: disease; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.disease (
    id integer NOT NULL,
    created_at timestamp(6) without time zone,
    created_by integer,
    deleted_at timestamp(6) without time zone,
    deleted_by integer,
    is_delete boolean,
    updated_at timestamp(6) without time zone,
    updated_by integer,
    description character varying(255),
    disease_code character varying(50),
    disease_name character varying(50),
    diseasename_en character varying(50),
    symptoms character varying(255),
    croptype_id integer,
    severity_level character varying(255),
    CONSTRAINT disease_severity_level_check CHECK (((severity_level)::text = ANY ((ARRAY['NHE'::character varying, 'TRUNG_BINH'::character varying, 'NANG'::character varying])::text[])))
);


ALTER TABLE public.disease OWNER TO postgres;

--
-- Name: disease_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.disease ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.disease_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: disease_weather_condition; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.disease_weather_condition (
    id integer NOT NULL,
    disease_id integer NOT NULL,
    condition_group character varying(50) NOT NULL,
    weather_factor character varying(50) NOT NULL,
    operator character varying(20) NOT NULL,
    min_value numeric(8,2),
    max_value numeric(8,2),
    unit character varying(20),
    risk_level character varying(50) NOT NULL,
    recommendation_note text,
    priority smallint,
    is_active boolean DEFAULT true,
    created_at timestamp(6) without time zone,
    created_by integer,
    updated_at timestamp(6) without time zone,
    updated_by integer,
    deleted_at timestamp(6) without time zone,
    deleted_by integer,
    is_delete boolean DEFAULT false
);


ALTER TABLE public.disease_weather_condition OWNER TO postgres;

--
-- Name: disease_weather_condition_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.disease_weather_condition_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.disease_weather_condition_id_seq OWNER TO postgres;

--
-- Name: disease_weather_condition_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.disease_weather_condition_id_seq OWNED BY public.disease_weather_condition.id;


--
-- Name: drug; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.drug (
    id integer NOT NULL,
    drug_name character varying(150) NOT NULL,
    formulation character varying(20),
    manufacturer character varying(150),
    is_active boolean DEFAULT true,
    created_at timestamp(6) without time zone,
    created_by integer,
    updated_at timestamp(6) without time zone,
    updated_by integer,
    deleted_at timestamp(6) without time zone,
    deleted_by integer,
    is_delete boolean DEFAULT false
);


ALTER TABLE public.drug OWNER TO postgres;

--
-- Name: drug_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.drug_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.drug_id_seq OWNER TO postgres;

--
-- Name: drug_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.drug_id_seq OWNED BY public.drug.id;


--
-- Name: drug_ingredient; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.drug_ingredient (
    id integer NOT NULL,
    drug_id integer NOT NULL,
    ingredient_id integer NOT NULL,
    concentration_value numeric(10,4),
    concentration_unit character varying(20),
    raw_concentration character varying(100),
    created_at timestamp(6) without time zone,
    created_by integer,
    updated_at timestamp(6) without time zone,
    updated_by integer,
    deleted_at timestamp(6) without time zone,
    deleted_by integer,
    is_delete boolean DEFAULT false
);


ALTER TABLE public.drug_ingredient OWNER TO postgres;

--
-- Name: drug_ingredient_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.drug_ingredient_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.drug_ingredient_id_seq OWNER TO postgres;

--
-- Name: drug_ingredient_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.drug_ingredient_id_seq OWNED BY public.drug_ingredient.id;


--
-- Name: drug_interaction; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.drug_interaction (
    id integer NOT NULL,
    ingredient_a_id integer NOT NULL,
    ingredient_b_id integer NOT NULL,
    interaction_type character varying(50),
    severity character varying(50),
    warning_message text NOT NULL,
    action_rule character varying(50),
    created_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP,
    created_by integer,
    updated_at timestamp(6) without time zone,
    updated_by integer,
    deleted_at timestamp(6) without time zone,
    deleted_by integer,
    is_delete boolean DEFAULT false,
    interval_days integer
);


ALTER TABLE public.drug_interaction OWNER TO postgres;

--
-- Name: drug_interaction_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.drug_interaction_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.drug_interaction_id_seq OWNER TO postgres;

--
-- Name: drug_interaction_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.drug_interaction_id_seq OWNED BY public.drug_interaction.id;


--
-- Name: ingredient; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ingredient (
    id integer NOT NULL,
    ingredient_name character varying(255) NOT NULL,
    description text,
    created_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP,
    created_by integer,
    updated_at timestamp(6) without time zone,
    updated_by integer,
    deleted_at timestamp(6) without time zone,
    deleted_by integer,
    is_delete boolean DEFAULT false
);


ALTER TABLE public.ingredient OWNER TO postgres;

--
-- Name: ingredient_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.ingredient_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.ingredient_id_seq OWNER TO postgres;

--
-- Name: ingredient_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.ingredient_id_seq OWNED BY public.ingredient.id;


--
-- Name: model_performance; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.model_performance (
    id integer NOT NULL,
    created_at timestamp(6) without time zone,
    created_by integer,
    deleted_at timestamp(6) without time zone,
    deleted_by integer,
    is_delete boolean,
    updated_at timestamp(6) without time zone,
    updated_by integer,
    accuracy numeric(5,4),
    avg_confidence_score numeric(5,4),
    f1_score numeric(5,4),
    low_confidence_count integer,
    metric_date timestamp(6) without time zone,
    "precision" numeric(5,4),
    recall numeric(5,4),
    total_diagnoses integer,
    model_id integer
);


ALTER TABLE public.model_performance OWNER TO postgres;

--
-- Name: model_performance_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.model_performance ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.model_performance_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notification; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notification (
    id integer NOT NULL,
    created_at timestamp(6) without time zone,
    created_by integer,
    deleted_at timestamp(6) without time zone,
    deleted_by integer,
    is_delete boolean,
    updated_at timestamp(6) without time zone,
    updated_by integer,
    content character varying(255),
    is_read boolean,
    notification_type character varying(255),
    read_at timestamp(6) without time zone,
    title character varying(255),
    user_id integer,
    CONSTRAINT notification_notification_type_check CHECK (((notification_type)::text = ANY ((ARRAY['CANH_BAO_BENH'::character varying, 'KET_QUA_CHAN_DOAN'::character varying, 'HE_THONG'::character varying])::text[])))
);


ALTER TABLE public.notification OWNER TO postgres;

--
-- Name: notification_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.roles (
    id integer NOT NULL,
    created_at timestamp(6) without time zone,
    created_by integer,
    deleted_at timestamp(6) without time zone,
    deleted_by integer,
    is_delete boolean,
    updated_at timestamp(6) without time zone,
    updated_by integer,
    description character varying(255),
    role_name character varying(50)
);


ALTER TABLE public.roles OWNER TO postgres;

--
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: treatment_plan; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.treatment_plan (
    id integer NOT NULL,
    created_at timestamp(6) without time zone,
    created_by integer,
    deleted_at timestamp(6) without time zone,
    deleted_by integer,
    is_delete boolean,
    updated_at timestamp(6) without time zone,
    updated_by integer,
    application_method text,
    application_time character varying(100),
    dosage character varying(100),
    dosage_per_ha_unit character varying(20),
    dosage_per_ha_value numeric(10,2),
    drug_name character varying(100),
    frequency character varying(100),
    is_required boolean,
    safety_notes text,
    treatment_name character varying(100),
    water_volume_per_ha character varying(50),
    disease_id integer,
    ingredient_id integer,
    drug_id integer,
    dosage_type character varying(20),
    dosage_value_min numeric(10,4),
    dosage_value_max numeric(10,4),
    dosage_unit character varying(20),
    dosage_area_value numeric(10,4),
    dosage_area_unit character varying(20),
    display_dosage character varying(200),
    mixing_instruction text,
    display_water_volume character varying(100),
    water_volume_min numeric(10,2),
    water_volume_max numeric(10,2),
    water_volume_unit character varying(10),
    spray_times smallint,
    spray_interval character varying(50),
    description text,
    is_active boolean DEFAULT true
);


ALTER TABLE public.treatment_plan OWNER TO postgres;

--
-- Name: treatment_plan_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.treatment_plan ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.treatment_plan_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: treatment_weather_condition; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.treatment_weather_condition (
    id integer NOT NULL,
    created_at timestamp(6) without time zone,
    created_by integer,
    deleted_at timestamp(6) without time zone,
    deleted_by integer,
    is_delete boolean,
    updated_at timestamp(6) without time zone,
    updated_by integer,
    is_required boolean,
    max_value numeric(10,2),
    min_value numeric(10,2),
    operator character varying(255),
    recommendation_note text,
    unit text,
    weather_factor character varying(255),
    treatment_id integer,
    CONSTRAINT treatment_weather_condition_operator_check CHECK (((operator)::text = ANY ((ARRAY['GREATER_THAN'::character varying, 'LESS_THAN'::character varying, 'BETWEEN'::character varying, 'EQUALS'::character varying])::text[]))),
    CONSTRAINT treatment_weather_condition_weather_factor_check CHECK (((weather_factor)::text = ANY ((ARRAY['TEMPERATURE'::character varying, 'HUMIDITY'::character varying, 'RAINFALL'::character varying, 'WIND_SPEED'::character varying])::text[])))
);


ALTER TABLE public.treatment_weather_condition OWNER TO postgres;

--
-- Name: treatment_weather_condition_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.treatment_weather_condition ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.treatment_weather_condition_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id integer NOT NULL,
    created_at timestamp(6) without time zone,
    created_by integer,
    deleted_at timestamp(6) without time zone,
    deleted_by integer,
    is_delete boolean,
    updated_at timestamp(6) without time zone,
    updated_by integer,
    email character varying(100),
    full_name character varying(100),
    is_active boolean,
    password_hash character varying(255),
    phone_number character varying(20),
    attachment_id integer,
    role_id integer
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: disease_weather_condition id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.disease_weather_condition ALTER COLUMN id SET DEFAULT nextval('public.disease_weather_condition_id_seq'::regclass);


--
-- Name: drug id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.drug ALTER COLUMN id SET DEFAULT nextval('public.drug_id_seq'::regclass);


--
-- Name: drug_ingredient id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.drug_ingredient ALTER COLUMN id SET DEFAULT nextval('public.drug_ingredient_id_seq'::regclass);


--
-- Name: drug_interaction id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.drug_interaction ALTER COLUMN id SET DEFAULT nextval('public.drug_interaction_id_seq'::regclass);


--
-- Name: ingredient id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ingredient ALTER COLUMN id SET DEFAULT nextval('public.ingredient_id_seq'::regclass);


--
-- Name: aimodel aimodel_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.aimodel
    ADD CONSTRAINT aimodel_pkey PRIMARY KEY (id);


--
-- Name: area_infor area_infor_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.area_infor
    ADD CONSTRAINT area_infor_pkey PRIMARY KEY (id);


--
-- Name: attachment attachment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.attachment
    ADD CONSTRAINT attachment_pkey PRIMARY KEY (id);


--
-- Name: chat_message chat_message_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat_message
    ADD CONSTRAINT chat_message_pkey PRIMARY KEY (id);


--
-- Name: chat_session chat_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat_session
    ADD CONSTRAINT chat_session_pkey PRIMARY KEY (id);


--
-- Name: crop_type crop_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.crop_type
    ADD CONSTRAINT crop_type_pkey PRIMARY KEY (id);


--
-- Name: diagnose_history_detail diagnose_history_detail_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.diagnose_history_detail
    ADD CONSTRAINT diagnose_history_detail_pkey PRIMARY KEY (id);


--
-- Name: diagnose_history diagnose_history_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.diagnose_history
    ADD CONSTRAINT diagnose_history_pkey PRIMARY KEY (id);


--
-- Name: diagnose_review diagnose_review_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.diagnose_review
    ADD CONSTRAINT diagnose_review_pkey PRIMARY KEY (id);


--
-- Name: disease disease_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.disease
    ADD CONSTRAINT disease_pkey PRIMARY KEY (id);


--
-- Name: disease_weather_condition disease_weather_condition_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.disease_weather_condition
    ADD CONSTRAINT disease_weather_condition_pkey PRIMARY KEY (id);


--
-- Name: drug_ingredient drug_ingredient_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.drug_ingredient
    ADD CONSTRAINT drug_ingredient_pkey PRIMARY KEY (id);


--
-- Name: drug_interaction drug_interaction_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.drug_interaction
    ADD CONSTRAINT drug_interaction_pkey PRIMARY KEY (id);


--
-- Name: drug drug_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.drug
    ADD CONSTRAINT drug_pkey PRIMARY KEY (id);


--
-- Name: ingredient ingredient_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ingredient
    ADD CONSTRAINT ingredient_pkey PRIMARY KEY (id);


--
-- Name: model_performance model_performance_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.model_performance
    ADD CONSTRAINT model_performance_pkey PRIMARY KEY (id);


--
-- Name: notification notification_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT notification_pkey PRIMARY KEY (id);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- Name: treatment_plan treatment_plan_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.treatment_plan
    ADD CONSTRAINT treatment_plan_pkey PRIMARY KEY (id);


--
-- Name: treatment_weather_condition treatment_weather_condition_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.treatment_weather_condition
    ADD CONSTRAINT treatment_weather_condition_pkey PRIMARY KEY (id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: drug_ingredient uk_drug_ingredient; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.drug_ingredient
    ADD CONSTRAINT uk_drug_ingredient UNIQUE (drug_id, ingredient_id);


--
-- Name: diagnose_review ukjl5d9pup0kwfnf2vyvrxd1u2b; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.diagnose_review
    ADD CONSTRAINT ukjl5d9pup0kwfnf2vyvrxd1u2b UNIQUE (history_id);


--
-- Name: drug_interaction uksxtlkh211q6yf27u531mb90i0; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.drug_interaction
    ADD CONSTRAINT uksxtlkh211q6yf27u531mb90i0 UNIQUE (ingredient_a_id, ingredient_b_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: idx_interaction_pair; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_interaction_pair ON public.drug_interaction USING btree (ingredient_a_id, ingredient_b_id);


--
-- Name: treatment_weather_condition fk7klhke67n2hvvfdpl2kh3mwgy; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.treatment_weather_condition
    ADD CONSTRAINT fk7klhke67n2hvvfdpl2kh3mwgy FOREIGN KEY (treatment_id) REFERENCES public.treatment_plan(id);


--
-- Name: treatment_plan fk9m2djmrj08bd167y2jrox2oxr; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.treatment_plan
    ADD CONSTRAINT fk9m2djmrj08bd167y2jrox2oxr FOREIGN KEY (ingredient_id) REFERENCES public.ingredient(id);


--
-- Name: disease_weather_condition fk_disease_weather_disease; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.disease_weather_condition
    ADD CONSTRAINT fk_disease_weather_disease FOREIGN KEY (disease_id) REFERENCES public.disease(id);


--
-- Name: drug_ingredient fk_drug_ingredient_drug; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.drug_ingredient
    ADD CONSTRAINT fk_drug_ingredient_drug FOREIGN KEY (drug_id) REFERENCES public.drug(id);


--
-- Name: drug_ingredient fk_drug_ingredient_ingredient; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.drug_ingredient
    ADD CONSTRAINT fk_drug_ingredient_ingredient FOREIGN KEY (ingredient_id) REFERENCES public.ingredient(id);


--
-- Name: drug_interaction fk_ingredient_a; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.drug_interaction
    ADD CONSTRAINT fk_ingredient_a FOREIGN KEY (ingredient_a_id) REFERENCES public.ingredient(id);


--
-- Name: drug_interaction fk_ingredient_b; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.drug_interaction
    ADD CONSTRAINT fk_ingredient_b FOREIGN KEY (ingredient_b_id) REFERENCES public.ingredient(id);


--
-- Name: chat_session fkd17ahlgqfllxn81i7mf3iiurs; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat_session
    ADD CONSTRAINT fkd17ahlgqfllxn81i7mf3iiurs FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: aimodel fkd7kvavnff4l0nvmbeak3v5om2; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.aimodel
    ADD CONSTRAINT fkd7kvavnff4l0nvmbeak3v5om2 FOREIGN KEY (croptype_id) REFERENCES public.crop_type(id);


--
-- Name: diagnose_history_detail fkec1udmvatecok39ddwhyrsoai; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.diagnose_history_detail
    ADD CONSTRAINT fkec1udmvatecok39ddwhyrsoai FOREIGN KEY (diagnosehistory_id) REFERENCES public.diagnose_history(id);


--
-- Name: users fkfthp39trtrm6qka2xb5ymbojx; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fkfthp39trtrm6qka2xb5ymbojx FOREIGN KEY (attachment_id) REFERENCES public.attachment(id);


--
-- Name: diagnose_review fkg3vnrsyh7kjlqg78qh5hppd79; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.diagnose_review
    ADD CONSTRAINT fkg3vnrsyh7kjlqg78qh5hppd79 FOREIGN KEY (history_id) REFERENCES public.diagnose_history(id);


--
-- Name: diagnose_history_detail fkgf5a9hafuw1nesuu5kk8dladp; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.diagnose_history_detail
    ADD CONSTRAINT fkgf5a9hafuw1nesuu5kk8dladp FOREIGN KEY (disease_id) REFERENCES public.disease(id);


--
-- Name: chat_message fkgtjn4wh83q8ohixkwcotpoob9; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat_message
    ADD CONSTRAINT fkgtjn4wh83q8ohixkwcotpoob9 FOREIGN KEY (session_id) REFERENCES public.chat_session(id);


--
-- Name: diagnose_history fkj232ppfdywoud7qev00vrxwfp; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.diagnose_history
    ADD CONSTRAINT fkj232ppfdywoud7qev00vrxwfp FOREIGN KEY (areainfo_id) REFERENCES public.area_infor(id);


--
-- Name: area_infor fklt8in672u4dwegx6vljt659fb; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.area_infor
    ADD CONSTRAINT fklt8in672u4dwegx6vljt659fb FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: disease fklxnpe13ysbw9l1trb34wejp9d; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.disease
    ADD CONSTRAINT fklxnpe13ysbw9l1trb34wejp9d FOREIGN KEY (croptype_id) REFERENCES public.crop_type(id);


--
-- Name: model_performance fkn2wsf5uf0ejv3ouuxitt3scw3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.model_performance
    ADD CONSTRAINT fkn2wsf5uf0ejv3ouuxitt3scw3 FOREIGN KEY (model_id) REFERENCES public.aimodel(id);


--
-- Name: notification fknk4ftb5am9ubmkv1661h15ds9; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT fknk4ftb5am9ubmkv1661h15ds9 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: diagnose_review fkox3a00q0ox8sdbc4u5jhjwm1t; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.diagnose_review
    ADD CONSTRAINT fkox3a00q0ox8sdbc4u5jhjwm1t FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: users fkp56c1712k691lhsyewcssf40f; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fkp56c1712k691lhsyewcssf40f FOREIGN KEY (role_id) REFERENCES public.roles(id);


--
-- Name: diagnose_history fkqa0940n7xjcvdghrri5oiisk6; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.diagnose_history
    ADD CONSTRAINT fkqa0940n7xjcvdghrri5oiisk6 FOREIGN KEY (croptype_id) REFERENCES public.crop_type(id);


--
-- Name: treatment_plan fktdb4x98jep6um9wws2awspl8k; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.treatment_plan
    ADD CONSTRAINT fktdb4x98jep6um9wws2awspl8k FOREIGN KEY (disease_id) REFERENCES public.disease(id);


--
-- Name: diagnose_history fktmqn8ks3qk7uey70h3tsk1s1h; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.diagnose_history
    ADD CONSTRAINT fktmqn8ks3qk7uey70h3tsk1s1h FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: treatment_plan treatment_plan_drug_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.treatment_plan
    ADD CONSTRAINT treatment_plan_drug_id_fkey FOREIGN KEY (drug_id) REFERENCES public.drug(id);


--
-- PostgreSQL database dump complete
--

\unrestrict nINp20zDhhKszaVVNoArGYu9zcLYodNc7VDl8OEMmp2lslEIYMR4UjQmKbFiP7y

