package com.phucnguyen.agriai.service;

import com.phucnguyen.agriai.dto.response.ChatMessageResponse;
import com.phucnguyen.agriai.entity.Attachment;
import com.phucnguyen.agriai.entity.ChatMessage;
import com.phucnguyen.agriai.entity.ChatSession;
import com.phucnguyen.agriai.enums.SenderType;
import com.phucnguyen.agriai.exception.AppException;
import com.phucnguyen.agriai.repository.AttachmentRepository;
import com.phucnguyen.agriai.repository.ChatMessageRepository;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

// It handles saving user/AI messages and retrieving chat history.
@Service
@RequiredArgsConstructor
@Transactional
public class ChatMessageService {

    private final ChatMessageRepository chatMessageRepository;
    private final ChatSessionService chatSessionService;
    private final AttachmentRepository attachmentRepository;
    private final AttachmentService attachmentService;

    @Transactional(readOnly = true)
    public Page<ChatMessageResponse> getMessages(String email, Integer sessionId, Pageable pageable) {
        ChatSession session = chatSessionService.getSessionOrThrow(email, sessionId);
        return chatMessageRepository.findByChatSessionIdAndChatSessionIsDeleteFalseOrderByCreatedAtAsc(session.getId(),
                pageable).map(ChatMessageResponse::fromEntity);
    }

    @Transactional(readOnly = true)
    public List<ChatMessage> getRecentMessages(ChatSession session, int limit) {
        Pageable pageable = PageRequest.of(0, limit);
        List<ChatMessage> messages = new ArrayList<>(
                chatMessageRepository.findByChatSessionIdAndChatSessionIsDeleteFalseOrderByCreatedAtDesc(
                        session.getId(), pageable));
        Collections.reverse(messages);
        return messages;
    }

    // Saves a message sent by the user (optionally with an attachment).
    public ChatMessage saveUserMessage(ChatSession session, String content, Integer attachmentId) {
        return saveMessage(session, SenderType.USER, content, attachmentId);
    }

    // Saves a message sent by the user (without attachment).
    public ChatMessage saveUserMessage(ChatSession session, String content) {
        return saveUserMessage(session, content, null);
    }

    // Saves a message generated by the AI.
    public ChatMessage saveAiMessage(ChatSession session, String content) {
        return saveMessage(session, SenderType.AI, content, null);
    }

    // Core method to persist a chat message into the database.
    private ChatMessage saveMessage(ChatSession session, SenderType senderType, String content, Integer attachmentId) {
        Attachment attachment = null;
        if (attachmentId != null) {
            attachment = attachmentRepository.findByIdAndIsDeleteFalse(attachmentId)
                    .orElseThrow(() -> new AppException(HttpStatus.NOT_FOUND, "Không tìm thấy tệp đính kèm với ID: " + attachmentId));
        }

        ChatMessage message = ChatMessage.builder()
                .chatSession(session)
                .senderType(senderType)
                .messageContent(content)
                .attachment(attachment)
                .build();

        ChatMessage savedMessage = chatMessageRepository.save(message);

        if (attachment != null) {
            attachmentService.linkAttachment(attachment.getId(), "CHAT_MESSAGE", savedMessage.getId());
        }

        return savedMessage;
    }
}

