package com.phucnguyen.agriai.service;

import com.phucnguyen.agriai.dto.response.ChatMessageResponse;
import com.phucnguyen.agriai.entity.ChatMessage;
import com.phucnguyen.agriai.entity.ChatSession;
import com.phucnguyen.agriai.enums.SenderType;
import com.phucnguyen.agriai.repository.ChatMessageRepository;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

// It handles saving user/AI messages and retrieving chat history.
@Service
@Transactional
public class ChatMessageService {

    private final ChatMessageRepository chatMessageRepository;
    private final ChatSessionService chatSessionService;

    public ChatMessageService(ChatMessageRepository chatMessageRepository, ChatSessionService chatSessionService) {
        this.chatMessageRepository = chatMessageRepository;
        this.chatSessionService = chatSessionService;
    }

    @Transactional(readOnly = true)
    public Page<ChatMessageResponse> getMessages(String email, Integer sessionId, Pageable pageable) {
        ChatSession session = chatSessionService.getSessionOrThrow(email, sessionId);
        return chatMessageRepository.findByChatSessionIdAndChatSessionIsDeleteFalseOrderByCreatedAtAsc(session.getId(),
                pageable).map(ChatMessageResponse::fromEntity);
    }

    @Transactional(readOnly = true)
    public List<ChatMessage> getRecentMessages(ChatSession session, int limit) {
        Pageable pageable = PageRequest.of(0, limit);
        List<ChatMessage> messages = new ArrayList<>(
                chatMessageRepository.findByChatSessionIdAndChatSessionIsDeleteFalseOrderByCreatedAtDesc(
                        session.getId(), pageable));
        Collections.reverse(messages);
        return messages;
    }

    // Saves a message sent by the user.
    public ChatMessage saveUserMessage(ChatSession session, String content) {
        return saveMessage(session, SenderType.USER, content);
    }

    // Saves a message generated by the AI.
    public ChatMessage saveAiMessage(ChatSession session, String content) {
        return saveMessage(session, SenderType.AI, content);
    }

    // Core method to persist a chat message into the database.
    private ChatMessage saveMessage(ChatSession session, SenderType senderType, String content) {
        ChatMessage message = ChatMessage.builder()
                .chatSession(session)
                .senderType(senderType)
                .messageContent(content)
                .build();
        return chatMessageRepository.save(message);
    }
}

