tunnel: 34137ba5-c38c-4c76-8e26-740b69fee2e8

credentials-file: /etc/cloudflared/34137ba5-c38c-4c76-8e26-740b69fee2e8.json

ingress:
  - hostname: agrismart.io.vn
    service: http://localhost:3000

  - service: http_status:404
