# Cổng chạy server Backend của bạn
server.port=8080

# Cấu hình kết nối PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/AgriAI_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:ThienPhuc2404}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${JWT_SECRET:YourSuperSecretKeyMinimum32CharactersLong!@#}
jwt.accessTokenExpiration=60
jwt.refreshTokenExpiration=10080

# Gemini LLM Configuration
gemini.api.key=${GEMINI_API_KEY:AIzaSyD1YKpGShO8r_JGCNKvakOMPqnu0OpmH88}
gemini.model.name=${GEMINI_MODEL:gemini-flash-latest}
auth.cookie.secure=${AUTH_COOKIE_SECURE:false}
auth.cookie.same-site=${AUTH_COOKIE_SAME_SITE:Lax}

# Cloudinary Configuration
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:dvee9ck25}
cloudinary.api-key=${CLOUDINARY_API_KEY:659554825837797}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:NNAoc3slCKMvE6Gxj1UTtlKQ06A}

# Weather API Configuration (OpenWeatherMap)
weather.api.key=${WEATHER_API_KEY:2d91360ce9d441502426fc1b5816203b}
deepseek.api.key=${DEEPSEEK_API_KEY:sk-3116fc5f05a64f7f96674d2b98a6042e}

# Vision AI Configuration (Local YOLO FastAPI)
vision.ai.url=${VISION_AI_URL:http://localhost:8010/predict}
